### ISSUE TITLE
stationary bootstrap fails tests sporadically

### ISSUE THREAD

**Issue by astrogilda** [astrogilda/tsbootstrap#82] opened 2024-02-26 16:58 UTC
due to misalignment between sampled_block_length and min_block_length.

**Comment by fkiraly** [comment] 2024-02-28 22:18
duplicate of #73?

**Comment by astrogilda** [comment] 2024-03-05 22:31
> duplicate of #73?

ah yes! this issue has a branch and a pr associated with it. how do I break those connections and reconnect them with #73 so i can delete this one?

**Comment by fkiraly** [comment] 2024-03-05 23:26
via click on this:
![image](https://github.com/astrogilda/tsbootstrap/assets/7985502/4ad68281-eb9d-49d6-9076-4edf408ffecd)
(right panel)

You could also connect the PR to both, issues automatically get closed when a connected PR is merged.

Also, btw, it's not your fault - it was originally named after `BaseBlockBootstrap`, but later I narrowed it down to `StationaryBlockBootstrap` and renamed the issue.

**Closed** 2024-03-20 14:46 UTC
